### ISSUE TITLE
Arrest / Civilian enhanced interaction

### ISSUE THREAD

**Issue by UncreatedLemon** [Giallustio/HeartsAndMinds#59]
I know it's a long shot, but have you considered adding in extra features / commands for civilians?
Also, there is a minor issue where people do not listen to you when you say 'get down' or 'stop'...that or the reputation level is low?

Thanks for the ACE feature update, has made the mission a lot more of a challenge for us!

**Comment by Vdauphin** [comment]
I am working on extra features like : 
- give order to civilian driver. You can ask to a civilan driver to stop his vehicle (https://github.com/Vdauphin/HeartsAndMinds/pull/55)
- you can ask to civilian driver to lift you to a location choosed on map (like taxi in city) if your reputation is higher than normal. (https://github.com/Vdauphin/HeartsAndMinds/pull/46), if you see enemy they will not attack you because the civilian driver is hiding you.
- you can now ask reputation to civilian (https://github.com/Vdauphin/HeartsAndMinds/pull/45)

All this new features are in developpement in my repository. I will do a pull request when they will be ready.

**Comment by UncreatedLemon** [comment]
awesome! Any chance of taking captive? (We like to play persistant, so our interpreter isn't always on, taking prisoners / wounded enemies captive and leaving them at base so when he gets on is something we are trying to do)

**Comment by Vdauphin** [comment]
I had a similar request from friends. I will open a pull request in my repository and see what I could do.

**Comment by Vdauphin** [comment]
the branch is https://github.com/Vdauphin/HeartsAndMinds/tree/Add-captive-enemies

**Comment by Giallustio** [comment]
Can i close it?

**Comment by Vdauphin** [comment]
For me, it is resolved!

**Comment by Giallustio** [comment]
@UncreatedLemon
